sap:
  connect:
    host: 0.0.0.0
    sysnr: 00
    client: 100
    user: SAP_USER
    passwd: SAP_PASSWORD
    lang: KO

# Server
jco:
  server:
    connection_count: 2
    progid: QH_SED
    repository_destination: ABAP_AS_WITHOUT_POOL
    gwserv: sapgw00
    gwhost: 0.0.0.0
    thread_count : 5