sap:
  connect:
    # 기본 연결 설정
    host: 0.0.0.0
    sysnr: 00
    client: 100
    user: SAP_USER
    passwd: SAP_PASSWORD
    lang: KO
    
    # 서버 설정
    serverName: SERVER
    gatewayHost: 0.0.0.0
    gatewayService: sapgw00
    programId: QH_SED
    connectionCount: 2
    threadCount: 5
    
    # Repository 설정
    repositoryDestination: ABAP_AS_WITHOUT_POOL

api:
  dev_url: http://localhost:8088
