spring:
  application:
    name: sap-jco-connector
  profiles:
    active: test-local
  output:
    ansi:
      enabled: always
  task:
    execution:
      pool:
        core-size: 5
        max-size: 5
        queue-capacity: 5
        keep-alive: 30s

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/saprfc_callinfo
    username: DB_USER
    password: DB_PASSWORD
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        column_ordering_strategy: legacy
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
  sql:
    init:
      mode: embedded

logging.level:
  org.hibernate.SQL: debug

sap:
  connect:
    # 기본 연결 설정
    host: ${SAP_HOST:localhost}
    sysnr: ${SAP_SYSNR:00}
    client: ${SAP_CLIENT:100}
    user: ${SAP_USER:SAP_USER}
    passwd: ${SAP_PASSWD:SAP_PASSWORD}
    lang: ${SAP_LANG:ko}
    poolCapacity: ${SAP_POOL_CAPACITY:3}
    peakLimit: ${SAP_PEAK_LIMIT:10}
    
    # 서버 설정
    serverName: ${SAP_SERVER_NAME:SERVER}
    gatewayHost: ${SAP_GW_HOST:localhost}
    gatewayService: ${SAP_GW_SERVICE:sapgw00}
    programId: ${SAP_PROG_ID:PROG_ID}
    connectionCount: ${SAP_CONNECTION_COUNT:2}
    threadCount: ${SAP_THREAD_COUNT:5}
    
    # Repository 설정
    repositoryDestination: ${SAP_REP_DEST:ABAP_AS_WITHOUT_POOL}

  rfc:
    connection:
      host: ${SAP_HOST:localhost}
      sysnr: ${SAP_SYSNR:00}
      client: ${SAP_CLIENT:100}
      user: ${SAP_USER:SAP_USER}
      passwd: ${SAP_PASSWD:SAP_PASSWORD}
      lang: ${SAP_LANG:KO}
      pool-capacity: ${SAP_POOL_CAPACITY:3}
      peak-limit: ${SAP_PEAK_LIMIT:10}
      gateway-host: ${SAP_GATEWAY_HOST:localhost}
      gateway-service: ${SAP_GATEWAY_SERVICE:sapgw00}
      program-id: ${SAP_PROGRAM_ID:ZFI_TAXINV_STATUS_TO_WEB}
      repository-destination: ${SAP_REPOSITORY_DESTINATION:ABAP_AS_WITHOUT_POOL}
      connection-count: ${SAP_CONNECTION_COUNT:2}
      thread-count: ${SAP_THREAD_COUNT:5}
    functions:
      - name: ZFI_TAXINV_STATUS_TO_WEB
        handler: taxInvoiceStateHandler
      # - name: ZFI_ANOTHER_FUNC
      #   handler: anotherHandler
      #   tables:
      #     - T_IF_ANOTHER